CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    img_path    VARCHAR(255),
    price       BIGINT        NOT NULL CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role     VARCHAR(20)  NOT NULL CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS cart_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL REFERENCES users (id),
    item_id  BIGINT NOT NULL REFERENCES items (id),
    quantity INT    NOT NULL CHECK (quantity > 0),
    UNIQUE (user_id, item_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES users (id),
    created_at TIMESTAMP NOT NULL,
    total_sum  BIGINT    NOT NULL CHECK (total_sum >= 0)
);

CREATE TABLE IF NOT EXISTS order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    item_id  BIGINT       NOT NULL REFERENCES items (id),
    title    VARCHAR(255) NOT NULL,
    price    BIGINT       NOT NULL CHECK (price >= 0),
    quantity INT          NOT NULL CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
