spring.application.name=auth-server

server.port=9000

spring.security.oauth2.authorizationserver.issuer=http://localhost:9000

spring.security.oauth2.authorizationserver.client.market-app.registration.client-id=market-app
spring.security.oauth2.authorizationserver.client.market-app.registration.client-name=Витрина интернет-магазина
spring.security.oauth2.authorizationserver.client.market-app.registration.client-secret={bcrypt}$2a$10$ICIan419WRadP5Ls1dOLR.P5.GQR/8EMGpfGM2K7lWIMYXrV2f1mm
spring.security.oauth2.authorizationserver.client.market-app.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.market-app.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.market-app.registration.scopes=payments
spring.security.oauth2.authorizationserver.client.market-app.token.access-token-time-to-live=5m

auth.resource-servers.payment-service=payments
