CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    img_path    VARCHAR(255),
    price       BIGINT        NOT NULL CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS cart_items
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL UNIQUE REFERENCES items (id),
    quantity INT   NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    total_sum  BIGINT    NOT NULL CHECK (total_sum >= 0)
);

CREATE TABLE IF NOT EXISTS order_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    item_id  BIGINT       NOT NULL REFERENCES items (id),
    title    VARCHAR(255) NOT NULL,
    price    BIGINT       NOT NULL CHECK (price >= 0),
    quantity INT          NOT NULL CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
